#! /bin/bash
# A bash script for installing WordPress from the command line
# Thanks to Navjot Singh - http://wp.tutsplus.com/tutorials/download-and-install-wordpress-via-the-shell-over-ssh/

# wget http://wordpress.org/latest.tar.gz  
# tar xfz latest.tar.gz
# mv wordpress/* ./ 
# rmdir ./wordpress/  
# rm -f latest.tar.gz  

usage()
		{
		echo "Install the latest version of WordPress into the current directory."	
		echo ""
		echo "usage: wpi [-h]"
		echo "  Example: wpi"
		echo ""
		echo "  -h, --help 			Print this help."
		echo "  -i, --install 		Install WordPress."
		echo ""
		exit 0
		}

install()
		{
		wget http://wordpress.org/latest.tar.gz  
		tar xfz latest.tar.gz	
		mv wordpress/* ./ 
		rmdir ./wordpress/  
		rm -f latest.tar.gz  
		}

while [ "$1" ]
do
	case "$1" in
		-h | --help )
			usage
			;;
		-i | --install )
			install
			;;
	esac
	shift
done

if [ -z "$1" ]
then	
		usage
		exit 0
fi



